# Generated by Django 5.0.2 on 2024-04-01 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('created_time',)},
        ),
        migrations.AddField(
            model_name='calendar',
            name='availability',
            field=models.CharField(choices=[('busy', 'Busy State'), ('moderate', 'Moderate State'), ('available', 'Available State')], default='busy', max_length=20),
        ),
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.TimeField(default='19:00'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='pollnode',
            name='users_voted',
            field=models.ManyToManyField(blank=True, related_name='voted_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='meeting',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='joinnode',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remindnode',
            name='message',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='remindnode',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('meeting', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('meeting', 'user')},
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='meetings.pollnode')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.pollnode')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
