# Generated by Django 5.0.3 on 2024-04-10 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias1', models.CharField(blank=True, max_length=20)),
                ('alias2', models.CharField(blank=True, max_length=20)),
                ('username1', models.CharField(blank=True, max_length=20)),
                ('username2', models.CharField(blank=True, max_length=20)),
                ('email1', models.CharField(blank=True, max_length=50)),
                ('email2', models.CharField(blank=True, max_length=50)),
                ('created', models.CharField(blank=True, max_length=10)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
